SOURCE TrainersAwards_CRUD/create_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/select_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/add_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/update_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/delete_TrainersAwards.sql;
