SOURCE TrainersAwards_CRUD/create_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/add_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/select_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/upd_TrainersAwards.sql;
SOURCE TrainersAwards_CRUD/del_TrainersAwards.sql;
