SOURCE Trainers_Pokemon/create_trainers_pokemon.sql;
SOURCE Trainers_Pokemon/add_trainers_pokemon.sql;
SOURCE Trainers_Pokemon/select_trainers_pokemon.sql;
SOURCE Trainers_Pokemon/update_trainers_pokemon.sql;
SOURCE Trainers_Pokemon/delete_trainers_pokemon.sql;
